### ISSUE TITLE
constant host nonce in mac command test routines

### ISSUE THREAD

**Issue by uzsunliming1** [MicrochipTech/cryptoauthlib#146] opened 2020-04-02 00:11 UTC
why we still use constant host nonce(20 bytes of 0x00) in test such as "mac_key_tempkey" and other tests in atca_tests_mac.c ?

**Comment by bryan-hunt** [comment] 2020-04-02 00:13
dupe of #145

**Closed by bryan-hunt** 2020-04-02 00:13 UTC
Labels: duplicate
