### ISSUE TITLE
memcpy to null address 

### ISSUE THREAD

**Issue by rspworks** [MicrochipTech/cryptoauthlib#259] opened 2021-09-20 10:31 UTC
Hello Bryan, 

https://github.com/MicrochipTech/cryptoauthlib/blob/b177b31182573f439191214d356a34f5db048beb/lib/calib/calib_sign.c#L241

Here `signature` is checked for NULL and then inside if it is memcpy with the destination as 'signature'.

Please check.

    if (ATCA_SUCCESS == status)
    {
        if (NULL == signature)
        {
            if (packet.data[ATCA_COUNT_IDX] == (ATCA_SIG_SIZE + ATCA_PACKET_OVERHEAD))
            {
                memcpy(signature, &packet.data[ATCA_RSP_DATA_IDX], ATCA_SIG_SIZE);
            }
            else
            {
                status = ATCA_RX_FAIL;
            }

        }
    }

Thanks,
Rohan

**Comment by bryan-hunt** [comment] 2021-09-20 10:50
Duplicate of #252

**Closed** 2021-09-20 10:50 UTC
Labels: duplicate
